import type { Metadata } from "next";
import Link from "next/link";
import type { ReactNode } from "react";
import { LiveWebVitals } from "@/components/client/LiveWebVitals";
import { ContributionGrid, LabelPill, MetaList } from "@/components/case-study/parts";
import { JsonLd } from "@/components/seo/JsonLd";
import { ButtonLink, Card, CheckList, Container, Eyebrow, TagList } from "@/components/ui/primitives";
import {
  appliedPerformance,
  challenges,
  contributions,
  coreWebVitals,
  engineeringPractices,
  outcomes,
  performancePractices,
  productImprovements,
  seoChecklist,
  tuskr,
} from "@/content/tuskr";
import { siteConfig } from "@/lib/site";
import { caseStudyJsonLd } from "@/lib/structured-data";

const path = `/case-studies/${tuskr.slug}`;
const description =
  "How Rahul Wakle builds and improves Tuskr, a test case management SaaS: React and TypeScript architecture, performance engineering, Core Web Vitals and technical SEO.";

export const metadata: Metadata = {
  title: `${tuskr.kicker}: ${tuskr.title}`,
  description,
  alternates: { canonical: path },
  openGraph: {
    type: "article",
    url: path,
    siteName: siteConfig.name,
    locale: siteConfig.locale,
    title: `${tuskr.kicker} — Case study`,
    description,
    authors: [siteConfig.name],
  },
  twitter: { title: `${tuskr.kicker} — Case study`, description },
};

const toc = [
  { id: "product", label: "Product & role" },
  { id: "built", label: "What I built" },
  { id: "challenges", label: "Challenges" },
  { id: "performance", label: "Performance" },
  { id: "web-vitals", label: "Core Web Vitals" },
  { id: "seo", label: "Technical SEO" },
  { id: "practices", label: "Product & practices" },
  { id: "impact", label: "Impact" },
];

const thisSite = [
  { title: "Server Components by default", body: "Every section is a Server Component. Only two small client islands ship JavaScript: the copy-email button and the live vitals panel above." },
  { title: "Statically prerendered", body: "Content lives in typed TypeScript modules, separate from UI. No API calls, no global state, no client-side data fetching." },
  { title: "Metadata API", body: "Title template, descriptions, canonical URLs, Open Graph and Twitter cards are generated by Next.js per route." },
  { title: "sitemap.ts · robots.ts", body: "The XML sitemap and robots.txt are generated from code, so new routes can't be forgotten." },
  { title: "JSON-LD", body: "Person and WebSite schema on the home page; Article and BreadcrumbList schema on this page." },
  { title: "next/font", body: "Geist is self-hosted at build time with a metric-matched fallback — no external font request, no layout shift." },
  { title: "next/og", body: "Social preview images are generated at build time from JSX, instead of shipping heavy raster files." },
  { title: "Accessible by structure", body: "Skip link, landmarks, one H1, ordered headings, visible focus, comfortable tap targets and reduced-motion support." },
];

type CaseSectionProps = { id: string; index: string; title: string; children: ReactNode; reveal?: boolean };

function CaseSection({ id, index, title, children, reveal = true }: CaseSectionProps) {
  return (
    <section id={id} aria-labelledby={`${id}-title`} className="scroll-mt-24 border-t border-line py-14 first:border-t-0 first:pt-0">
      <div className={reveal ? "reveal" : undefined}>
        <Eyebrow className="text-accent">§ {index}</Eyebrow>
        <h2 id={`${id}-title`} className="mt-3 mb-8 text-2xl font-semibold tracking-tight text-balance sm:text-3xl">
          {title}
        </h2>
      </div>
      {children}
    </section>
  );
}

export default function TuskrCaseStudyPage() {
  return (
    <>
      <JsonLd data={caseStudyJsonLd()} />
      <article>
        <header className="relative overflow-hidden border-b border-line">
          <div aria-hidden="true" className="grid-backdrop absolute inset-0 -z-10" />
          <Container className="pt-10 pb-16 sm:pt-14 sm:pb-20">
            <nav aria-label="Breadcrumb">
              <ol className="flex items-center gap-2 font-mono text-xs text-muted">
                <li>
                  <Link href="/" className="hover:text-accent">
                    Home
                  </Link>
                </li>
                <li aria-hidden="true">/</li>
                <li>
                  <Link href="/#tuskr" className="hover:text-accent">
                    Case studies
                  </Link>
                </li>
                <li aria-hidden="true">/</li>
                <li aria-current="page" className="text-text">
                  Tuskr
                </li>
              </ol>
            </nav>
            <Eyebrow className="mt-10 text-accent">{tuskr.kicker}</Eyebrow>
            <h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight text-balance sm:text-6xl">{tuskr.title}</h1>
            <p className="mt-5 max-w-2xl text-xl text-muted">“{tuskr.tagline}”</p>
            <div className="mt-8">
              <TagList items={tuskr.stack} tone="accent" label="Tech stack" />
            </div>
            <div className="mt-10 border-t border-line pt-8">
              <MetaList items={tuskr.meta} />
            </div>
          </Container>
        </header>

        <Container className="grid gap-12 py-16 lg:grid-cols-[13rem_1fr]">
          <aside className="hidden lg:block">
            <nav aria-label="On this page" className="sticky top-24">
              <p className="mb-4 font-mono text-xs uppercase tracking-[0.18em] text-muted">On this page</p>
              <ol className="space-y-1 border-l border-line text-sm">
                {toc.map((item, i) => (
                  <li key={item.id}>
                    <a href={`#${item.id}`} className="-ml-px flex gap-3 border-l border-transparent py-1.5 pl-4 text-muted transition-colors hover:border-accent hover:text-text">
                      <span aria-hidden="true" className="font-mono text-xs leading-5 text-accent/70">
                        {String(i + 1).padStart(2, "0")}
                      </span>
                      {item.label}
                    </a>
                  </li>
                ))}
              </ol>
            </nav>
          </aside>

          <div className="min-w-0">
            <CaseSection id="product" index="01" title="The product & my role" reveal={false}>
              <div className="grid gap-4 md:grid-cols-2">
                <Card>
                  <h3 className="font-mono text-xs uppercase tracking-[0.18em] text-muted">The product</h3>
                  <p className="mt-3 leading-relaxed">{tuskr.product}</p>
                </Card>
                <Card>
                  <h3 className="font-mono text-xs uppercase tracking-[0.18em] text-muted">My role</h3>
                  <p className="mt-3 leading-relaxed">{tuskr.role}</p>
                </Card>
              </div>
              <p className="mt-4 flex gap-2 text-xs leading-relaxed text-muted">
                <span aria-hidden="true">🔒</span>
                {tuskr.confidentiality}
              </p>
            </CaseSection>

            <CaseSection id="built" index="02" title="What I built">
              <ContributionGrid items={contributions} />
            </CaseSection>

            <CaseSection id="challenges" index="03" title="Engineering challenges → how I approach them">
              <ol className="reveal-stagger divide-y divide-line overflow-clip rounded-2xl border border-line">
                {challenges.map((item) => (
                  <li key={item.challenge} className="grid gap-2 p-5 sm:grid-cols-[14rem_1fr] sm:gap-6">
                    <h3 className="font-semibold tracking-tight">{item.challenge}</h3>
                    <p className="text-sm leading-relaxed text-muted">{item.approach}</p>
                  </li>
                ))}
              </ol>
            </CaseSection>

            <CaseSection id="performance" index="04" title="Performance engineering">
              <div className="flex flex-wrap items-center gap-3">
                <h3 className="text-lg font-semibold">Applied in production</h3>
                <LabelPill>From my work</LabelPill>
              </div>
              <ul className="reveal-stagger mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {appliedPerformance.map((item) => (
                  <Card as="li" key={item.title} className="border-accent/25">
                    <h4 className="font-semibold">{item.title}</h4>
                    <p className="mt-2 text-sm leading-relaxed text-muted">{item.body}</p>
                  </Card>
                ))}
              </ul>

              <div className="mt-12 flex flex-wrap items-center gap-3">
                <h3 className="text-lg font-semibold">Practices I follow</h3>
                <LabelPill tone="warn">Engineering practice</LabelPill>
              </div>
              <p className="mt-2 max-w-2xl text-sm text-muted">
                The general principles I use to keep a React application fast as it grows — applied where they fit, not
                everywhere by default.
              </p>
              <div className="reveal-stagger mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {performancePractices.map((group) => (
                  <Card key={group.group}>
                    <h4 className="mb-4 font-mono text-xs uppercase tracking-[0.18em] text-muted">{group.group}</h4>
                    <CheckList items={group.items} />
                  </Card>
                ))}
              </div>
            </CaseSection>

            <CaseSection id="web-vitals" index="05" title="Core Web Vitals: where frontend decisions show up">
              <div className="reveal-stagger grid gap-4 lg:grid-cols-3">
                {coreWebVitals.map((vital) => (
                  <Card key={vital.short} className="flex flex-col">
                    <div className="flex items-baseline justify-between gap-3">
                      <h3 className="text-2xl font-semibold tracking-tight">{vital.short}</h3>
                      <span className="font-mono text-xs text-accent">good {vital.good}</span>
                    </div>
                    <p className="mt-1 text-sm font-medium">{vital.name}</p>
                    <p className="mt-1 mb-5 text-sm text-muted">{vital.measures}</p>
                    <h4 className="mb-3 font-mono text-xs uppercase tracking-[0.18em] text-muted">What moves it</h4>
                    <CheckList items={vital.levers} />
                  </Card>
                ))}
              </div>
              <div className="reveal mt-8">
                <LiveWebVitals />
              </div>
            </CaseSection>

            <CaseSection id="seo" index="06" title="Technical SEO, as an engineering requirement">
              <p className="mb-8 max-w-2xl text-muted">
                SEO is mostly good engineering: content a crawler can read, metadata that describes it, and pages fast
                enough that people stay. No keyword stuffing, nothing that trades UX for rankings.
              </p>
              <div className="reveal-stagger grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {seoChecklist.map((group) => (
                  <Card key={group.group}>
                    <h3 className="mb-4 font-mono text-xs uppercase tracking-[0.18em] text-muted">{group.group}</h3>
                    <CheckList items={group.items} />
                  </Card>
                ))}
              </div>

              <div id="this-site" className="reveal mt-12 scroll-mt-24 rounded-2xl border border-accent/30 bg-surface p-6 sm:p-8">
                <div className="flex flex-wrap items-center gap-3">
                  <h3 className="text-lg font-semibold">How this portfolio implements it</h3>
                  <LabelPill>Verifiable — view source</LabelPill>
                </div>
                <ul className="mt-6 grid gap-x-8 gap-y-5 sm:grid-cols-2">
                  {thisSite.map((item) => (
                    <li key={item.title}>
                      <h4 className="font-mono text-sm text-accent">{item.title}</h4>
                      <p className="mt-1 text-sm leading-relaxed text-muted">{item.body}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </CaseSection>

            <CaseSection id="practices" index="07" title="Product improvements & engineering practices">
              <div className="reveal-stagger grid gap-4 md:grid-cols-2">
                <Card>
                  <h3 className="mb-4 font-semibold">Product & UI improvements</h3>
                  <CheckList items={productImprovements} />
                </Card>
                <Card>
                  <h3 className="mb-4 font-semibold">Engineering practices</h3>
                  <CheckList items={engineeringPractices} />
                </Card>
              </div>
            </CaseSection>

            <CaseSection id="impact" index="08" title="Result & impact">
              <dl className="reveal grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">
                {outcomes.map((item) => (
                  <div key={item.label} className="flex flex-col gap-2 bg-surface p-6">
                    <dt className="text-sm leading-relaxed text-muted">{item.label}</dt>
                    <dd className="order-first text-3xl font-semibold tracking-tight">
                      {item.value}
                      {item.measured && <span className="ml-2 align-middle font-mono text-xs font-normal text-accent">résumé figure</span>}
                    </dd>
                  </div>
                ))}
              </dl>
              <p className="mt-4 text-xs text-muted">
                Only one outcome is quantified because only one is measured. The rest are described qualitatively rather than
                invented.
              </p>

              <div className="reveal mt-14 flex flex-col gap-6 rounded-2xl border border-line bg-surface p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8">
                <p className="text-xl font-semibold tracking-tight text-balance">Want the deeper walkthrough? I’m happy to talk through it.</p>
                <div className="flex flex-wrap gap-3">
                  <ButtonLink href="/#contact">Get in touch</ButtonLink>
                  <ButtonLink href="/" variant="ghost">
                    Back to home
                  </ButtonLink>
                </div>
              </div>
            </CaseSection>
          </div>
        </Container>
      </article>
    </>
  );
}
